### PR TITLE
Df lu2629 calc top two

### PR DESCRIPTION
**Pull request by Dom-Ford**
For @Jordancooke  to review as agreed. Happy to discuss anything that looks odd, or any of the new validation checks in the wrangler.

### CODE REVIEW

**Comment by Jordancooke** [comment]
Test & Linter pass, 100% coverage. Good stuff

Overall code is good and have no faults with the logic. Some needed additions to the exceptions have been added which are a welcome change.

I have a few things which are mostly just formatting, and after speaking with Dom it seems to be down to line length not being correctly configured (all been there).

Code
—
- Comments un-indent by one to be in line with the other comments.
- Method - On the returns could you please specify both the name of the returned items and the type.
- Line 58 - The comment might be a bit redundant as most of the devs should know this and it’s basically the size of half the exception
- line 95, 97, 106, 120, 125, 137, 139, 144, 146 - Can easily all fit on one line
- Wrangler - line 96, 97 + 132, 133 - Just use one line not +=
- Line 105 - When possible can we use the full words, just for readability.
- Line 126 - Can all fit on one line.
- Line 235 - send_sns_message is missing a doc string

Test’s
—
- Name the test class something different (Know It’s wrong in many others)
- Wrangler - line 170 - Can you bring the mock lambda up onto the line above.
- Wrangler- Line 19, 131, 211, 252, 291, 364, 407, 408 - Can all fit comfortably on one line.
- Method - Line 17, 41 -Could you try and reformat to move the / if possible.
- Wrangler - line 367 - Could you try and reformat to move the / if possible.
- Wrangler - Line 148 -  Bit of a rouge closing bracket  in the middle of the line.
- Comments un-indent by one to be in line with the other comments.
- Can we remove these lines between tests just so it seems more uniform.

Give me a shout if anything is unclear, also some of the line numbers may be out by one or two due to some on fly editing.

**Comment by Dom-Ford** [comment]
CODE

- [ ] Comments un-indent by one to be in line with the other comments.
- [ ] Method - On the returns could you please specify both the name of the returned items and the type.
- [ ] Line 58 - The comment might be a bit redundant as most of the devs should know this and it’s basically the size of half the exception
- [ ] line 95, 97, 106, 120, 125, 137, 139, 144, 146 - Can easily all fit on one line
- [ ] Wrangler - line 96, 97 + 132, 133 - Just use one line not +=
- [ ] Line 105 - When possible can we use the full words, just for readability.
- [ ] Line 126 - Can all fit on one line.
- [ ] Line 235 - send_sns_message is missing a doc string

TESTS

- [ ] Name the test class something different (Know It’s wrong in many others)
- [ ] Wrangler - line 170 - Can you bring the mock lambda up onto the line above.
- [ ] Wrangler- Line 19, 131, 211, 252, 291, 364, 407, 408 - Can all fit comfortably on one line.
- [ ] Method - Line 17, 41 -Could you try and reformat to move the / if possible.
- [ ] Wrangler - line 367 - Could you try and reformat to move the / if possible.
- [ ] Wrangler - Line 148 - Bit of a rouge closing bracket in the middle of the line.
- [ ] Comments un-indent by one to be in line with the other comments.
- [ ] Can we remove these lines between tests just so it seems more uniform.

**Comment by Dom-Ford** [comment]
Notes: 

- Fixed my flake8 line config from 79 to 89 chars and have rejigged the line wraps. Some remained for legibility within key/value pairs in json/dicts.

- Line 105: index is a function keyword, hence use of "idx" to identify the index of the row currently being iterated over. (I was trying to provide more readability that the usual "i" usage.) Have changed all instances of idx to "row_index".

- All backslash wraps removed and replaced with parenthesised constructions or "+=" incremental builds as appropriate.

**Comment by thomashenson** [comment]
Following on from Jordans review, pretty much everything has been taken care of here. The only thing I would suggest is that in the tests, where you are mocking environment variables, that instead of re-writing them in each test you use a mock class that makes them available to all functions within the file. See below:

Essentially, all you need to do is add the two class methods at the top of your test class definition, like so:

```
class TestClass(...):
    ...
    @classmethod
    def setup_class(cls):
        cls.mock_os_patcher = mock.patch.dict(
            "os.environ",
            {
                "env_var_1": "mock-bucket",
                "env_var_2": "mock-file",
                ...
            },
        )

        cls.mock_os_patcher.start()

    @classmethod
    def teardown_class(cls):
        # Stop the mocking of the os stuff
        cls.mock_os_patcher.stop()

    ...
```

This should remove the need for you to re-write your env vars in each function. Works a treat! Let me know if you get stuck with this. Happy to help.

**Comment by Dom-Ford** [comment]
Have tried this out with Tom, it causes the test to fail.  Tom will check it out at a later date as tech debt, but we have decided to leave the tests in a working condition and complete the merge. As the russians say, "Excellence" is the enemy of "Good Enough".

**Comment by Dom-Ford** [comment]
@thomashenson : If you are happy we have done what we need to, can you approve please. Once approved, I will merge. 
Cheers.

**Pull request merged**
